Task 9
DmitryVDV/flashcards pull request #8
Opened 2017-05-21 17:05 UTC by DmitryVDV

2017-05-29 13:28 UTC, X1ting requested changes

2017-05-29 13:28 UTC, X1ting commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
зачем оставляешь пустые файлы?

2017-05-29 13:28 UTC, X1ting commented on app/controllers/users_controller.rb
> +require 'pry'
это реально нужно?

2017-05-29 13:28 UTC, X1ting commented on app/controllers/users_controller.rb
> +require 'pry'
ну вот эти все три строки

2017-05-29 13:28 UTC, X1ting commented on spec/factories/users.rb
> +    sequence(:email) { |n| "someone#{rand(1..100000000)}@mail.com" }
у тебя же есть n переменная, которая отвечает за уникальность, зачем еще rand дергать

2017-05-29 13:28 UTC, X1ting commented on spec/factories/users.rb
> +    sequence(:uid) { |n| rand(1000000..10000000) }
тут тоже самое

2017-05-29 13:28 UTC, X1ting commented on spec/interactor/card_update_reviewdate.rb
> +      expect(page).to have_content("Перевод верный", wait:15)
wait:15 тощно без пробела должно писаться?

2017-05-29 13:28 UTC, X1ting commented on app/controllers/users_controller.rb
> +  def user_params_password
лучша наверное будет выглядеть как password_params и email_params сверху

2017-05-29 13:32 UTC, DmitryVDV commented on spec/factories/users.rb
> +    sequence(:email) { |n| "someone#{rand(1..100000000)}@mail.com" }
n всегда с 1 начинается, а база у меня не очищается тестовая, на уникальности вылетает тест. Поэтому рандомно сделал.

2017-05-29 13:32 UTC, DmitryVDV commented on spec/interactor/card_update_reviewdate.rb
> +      expect(page).to have_content("Перевод верный", wait:15)
исправлю

2017-05-29 13:33 UTC, X1ting commented on spec/factories/users.rb
> +    sequence(:email) { |n| "someone#{rand(1..100000000)}@mail.com" }
а database_cleaner не пробовал?

2017-05-29 13:42 UTC, DmitryVDV commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
уберу

2017-05-29 13:43 UTC, DmitryVDV commented on app/controllers/users_controller.rb
> +require 'pry'
уберу

2017-05-29 13:45 UTC, DmitryVDV commented on app/controllers/users_controller.rb
> +  def user_params_password
поправлю

2017-05-29 15:07 UTC, X1ting commented on app/controllers/cards_controller.rb
> +    if user.cards.create!(card_params)
а зачем create! а не create

2017-05-29 15:13 UTC, X1ting approved these changes

2017-05-30 15:32 UTC, X1ting requested changes

2017-05-30 15:32 UTC, X1ting commented on app/controllers/cards_controller.rb
> +    @cards = Card.where(user_id: current_user.id)
why not `current_user.cards` ?

2017-05-30 15:32 UTC, X1ting commented on app/controllers/cards_controller.rb
> +    user = User.find(current_user.id)
what reason for it? why you not use `current_user`

2017-05-30 15:32 UTC, X1ting commented on app/controllers/users_controller.rb
> +    @user = User.find(current_user.id)
why not `@user = current_user` ?

2017-05-30 15:32 UTC, X1ting commented on app/controllers/users_controller.rb
> +    @user = User.find(current_user.id)
why not @user = current_user ?
and if you do it multiple times, better move to before_action

2017-05-30 15:32 UTC, X1ting commented on app/interactors/show_user_card.rb
> +    # uid fields when creating a new user. The first_or_create! method operates
its usefull comment?

2017-05-30 15:32 UTC, X1ting commented on app/models/card.rb
> +    # Unicode must edit via  mb_chars !
useless comment

2017-05-30 15:32 UTC, X1ting commented on app/views/devise/registrations/new.html.erb
> +<h2>Регистрация</h2>
malformed indentation in this file

2017-05-30 15:32 UTC, X1ting commented on app/views/devise/sessions/new.html.erb
> +<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
indentations

2017-05-30 15:32 UTC, X1ting commented on app/views/users/update_password.html.erb
> +<h1>Users#update_password</h1>
useless file

2017-05-30 15:32 UTC, X1ting commented on spec/views/users/edit.html.erb_spec.rb
> +DatabaseCleaner.strategy = :truncation, {:only => %w[users cards]}
you can move DatabaseCleaner setup to rails_helper, and forget about it)

2017-05-30 15:32 UTC, X1ting commented on spec/views/users/edit.html.erb_spec.rb
> +RSpec.describe 'users/edit.html.erb', type: :feature do
just `describe`
Why `type: :feature` in spec/views ?

2017-05-30 15:32 UTC, X1ting commented on app/views/users/_userform.html.erb
> +<div class="container">
indentation
and always files like this, called _form.html.erb

2017-05-30 15:34 UTC, X1ting requested changes

2017-05-30 15:34 UTC, X1ting commented on app/controllers/cards_controller.rb
> +    puts card_params
`puts` ?

2017-06-05 16:55 UTC, merged